### ISSUE TITLE
Article not found

### ISSUE THREAD

**Issue by CBenoit** [Michael-F-Bryan/modern-webassembly#1]
Hello!

When trying to access the article at https://adventures.michaelfbryan.com/posts/using-webassembly-in-the-modern-world/, I get a 404 not found error.
I’m curious to know why the article has been removed if it’s intentional.

Thank you!

**Comment by Michael-F-Bryan** [comment]
I'm curious to know how you found that link because it hasn't been published (or even completed!) yet.

**Comment by CBenoit** [comment]
Oh that's why haha!
I just stumbled upon this repository when looking for https://github.com/Michael-F-Bryan/rust-ffi-guide in your profile.
